### ISSUE TITLE
Error:(617) Attribute "alpha" has already been defined

### ISSUE THREAD

**Issue by FanYimin** [yushiwo/QrScan#1]
E:\advertisement\xxxxxx\app\build\intermediates\res\merged\debug\values\values.xml
Error:(617) Attribute "alpha" has already been defined
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
Information:BUILD FAILED
Information:Total time: 1.317 secs
Information:3 errors
Information:0 warnings
Information:See complete output in console

**Comment by yushiwo** [comment]
组件没有提供设置alpha属性的接口，我这边拉demo跑了一下也是没有问题的。你看看是不是库版本不对造成的？   可以参考下这个：https://github.com/mikepenz/MaterialDrawer/issues/1498

**Comment by FanYimin** [comment]
谢谢，应该是DrawerLayout 冲突，
我使用了me.fangx.common的公共组件
common-res-values-attr里面是有alpha的

**Comment by yushiwo** [comment]
😄，不客气。解决问题才是主要的～
